### ISSUE TITLE
Fix: Mocks for a protocol with associated type constrained by `where` clause

### ISSUE THREAD

**Issue by SergeyKovalenko** [MakeAWishFoundation/SwiftyMocky#137]
Is there any way for generating mock for a protocol like this:
```swift
protocol ProtocolWithAssociatedType {
  associatedtype T: Sequence where T.Element: Equatable
  
  var sequence: T { get }
  
  func methodWithType(t: T) -> Bool
}
```
Looks like mock template can't handle `where` clause  in `associatedtype` annotayion:
```
//sourcery: AutoMockable
//sourcery: associatedtype = "T: Sequence where T.Element: Equatable"
```

**Comment by amichnia** [comment]
@SergeyKovalenko the fix is temporarily on `release/3.0.0` branch. We are aiming to have it reviewed and released by the end of the week. 

If you really need it, you might check this branch out, I'll be glad for any feedback regarding SwiftyMocky 3.0. Just please have in mind, that as we are still working on it, it might be subject of changes.
