### ISSUE TITLE
How to stub and return values for things that you don't own ex UIApplication,UIDevice

### ISSUE THREAD

**Issue by repl-ullas-ml** [MakeAWishFoundation/SwiftyMocky#176]

**Comment by amichnia** [comment]
@repl-ullas-ml the idea of SwiftyMocky is to simplify unit testing, by providing mock generation. We want to encourage to do the unit testing right - which also means to provide proper layer separation. To do it, you should interface everything, that could be a dependency.

In other worlds, if you have `UIDevice`, you should create `Device` protocol which describes desired features. Then you can make `UIDevice` adopt `Device` protocol.

That allows to:
1. Have proper layer separation and testability
2. Allows to easily create mocks or stubs (whether with SwiftyMocky or manually)

There is a very good reason why we did not allow to mock concrete classes - it is because we cannot guarantee that mock would be valid. Especially, that some methods or properties might be `final`. Mocking methods from extensions could also be tricky. 

In general - we decided we don't want half-solutions, and we do not consider "partial mock" a mock at all.

Please note, that there is some possibility we would add some kind of class mocking features in the future, but only if we are sure it would be providing more value than problems.
