### ISSUE TITLE
Migration guide from 3.2.0

### ISSUE THREAD

**Issue by darecki** [MakeAWishFoundation/SwiftyMocky#193]
As there is a lot of changes in version 3.3.0 it would be nice to add a migration guide. 
In particular: am I forced to use the new CLI or can I generate mocks as I did in earlier versions?

**Comment by amichnia** [comment]
@darecki I will work on it. Until its ready, I'll keep this issue opened. You are right that we might want to have this info more visible.

To answer your question, the migration is not required. Please look into [Legacy](https://github.com/MakeAWishFoundation/SwiftyMocky/blob/master/guides/Legacy.md) section in guide. You can still use it as it was, that's why it's 3.3.x not 4.0.0.

New CLI is more a feature, as it solves many problems, like:
1. Wrong Sourcery version
2. Verbose setup, now in most projects `SwiftyMocky setup` should be sufficient
3. Simplified generation - previous it needed additional wrapping up, as you need to have path to template and Sourcery, which were different depending on the setup
4. Easier handling projects with multiple test targets. All is now in one Mockfile, instead of keeping separate configurations for each mock generated
5. Even in scope on the same target, you can split mocks into separate files if it makes sense for some reasons (like type names collisions)

Anyway, I really encourage to try the CLI, and wait for feedback :)

**Comment by darecki** [comment]
@amichnia thanks for a great answer! I will definitely try the CLI, but for now I needed to quickly regenerate mocks. It turned out the updating Sourcery solved the problem in my case.

One more thing I'd definitely like to see in the migration guide is how to migrate from mocky.yml to the Mockfile.

**Comment by amichnia** [comment]
@darecki try `swiftymocky setup` (it should ask about migration), or directly `swiftymocky migrate`

You can then run `swiftymocky doctor` to verify if all is fine. Mockfile should also seem familiar, of you used the previous configurations :)

**Comment by amichnia** [comment]
Migration is now explicitly referred from Readme. Closing.

**Comment by darecki** [comment]
Perfect. Thanks!
