### ISSUE TITLE
No such module for several imports, SwiftyMocky 3.3.3

### ISSUE THREAD

**Issue by PlamenPenchev** [MakeAWishFoundation/SwiftyMocky#204]
I wonder if this is an issue from the setup on my side, but Xcode does not recognise several imports from Mock.generated.swift. I have installed mint and the CLI. Run setup and generate. Doctor finds no issues also.

<img width="1272" alt="Screenshot 2019-06-27 at 15 27 42" src="https://user-images.githubusercontent.com/26491599/60266797-7b9df300-98f1-11e9-9077-9c8dae7af0dc.png">

**Comment by amichnia** [comment]
@PlamenPenchev please verify your Mockfile.

As I see, you most probably include Pods directory in the `include` section. That results in generating mocks and capturing imports also from Pods, and since we use SwiftyMocky to test CLI, it captures several of our internal dependincies.

Try to add Pods directory to `exclude` sources section in the Mockfile, as described in [guides](https://github.com/MakeAWishFoundation/SwiftyMocky/blob/master/guides/Mockfile.md)

**Comment by amichnia** [comment]
@PlamenPenchev after updating mockfile you might need to run `swiftymocky autoimport` to update imports automatically.

You can also always remove them directly from the Mockfile, from the imports section.

**Comment by PlamenPenchev** [comment]
That was the issue, adding pods in exclude fixed it. This can be closed I guess. Thank You!
