### ISSUE TITLE
Missing matcher registration should not crash the test runner

### ISSUE THREAD

**Issue by forceunwrap** [MakeAWishFoundation/SwiftyMocky#227]
Hi.

First of all, thanks for the awesome lib.

Currently, when you try to match custom types which are not `Equatable`, the test runner will crash and print a message which says that there is a Matcher registration missing. Sometimes you can't even see this error message, because the test runner sometimes immediately reboots itself, which also clears the console log.
Another problem with the "crashing" approach is that if you run the test suite on CI the crash will cause the build to fail, because obviously the runner stopped working. This shouldn't be happening that often because you run your tests locally when writing them anyway, but still.

So my question is:
Is it (easily) possible to only fail the affected test and throw an appropriate error message?

Thanks

**Comment by amichnia** [comment]
@forceunwrap thanks for raising it. I will try to make it fail the test instead. The not crashing part might be tricky. Theoretically, if you set your tests not to continue after failure, it should work (so it would not get to the crash since it will finish the test on failure just before). 

I was also thinking of causing failure and returning false as default, but I'm not sure if that is a good approach yet. I need to see if there is any chance of running into "accidentally" passing tests.

**Comment by g-amichnia** [comment]
Matcher should fail more gracefully now. Still - it might not work in the first test executed, so for best results call to `SwiftyMockyTestObserver.setup()` would be recommended.
