### ISSUE TITLE
Mocks for protocols with `#if os(xxx)` don't build.

### ISSUE THREAD

**Issue by laxmorek** [MakeAWishFoundation/SwiftyMocky#271]
### Problem

`Mock.generated.swift` doesn't build when protocol with annotation `// sourcery: AutoMockable` contains `#if os(xxx)` statement.

### Expected behavior 

`Mock.generated.swift` should handle `#if os(xxx)`.

### Environment

- `SwiftyMocky` - `4.0.1`
- `Sourcery` - `1.0.0`
- `Xcode` - `12.2`
- `macOS` - `11.0.1 `

### Example

**Input:**

```swift
// sourcery: AutoMockable
public protocol Foo {
    func foo()
    
    #if os(iOS)
    func bar()
    #endif
}
```

**Output:**

<img width="1270" alt="Screenshot 2020-12-02 at 10 42 26" src="https://user-images.githubusercontent.com/4774319/100999967-9603e380-355d-11eb-872f-6485f6df232a.png">

<img width="1274" alt="Screenshot 2020-12-02 at 10 43 01" src="https://user-images.githubusercontent.com/4774319/100999976-97cda700-355d-11eb-9769-d33fbd4b3f39.png">

**Comment by g-amichnia** [comment]
Same goes with #if DEBUG etc. The problem is with source kitten I suppose. Not much we can do about it at this point. 

Just a general remark,  I would strongly recommend avoiding that. You can always use `@available` statement instead of conditional compilation. It is better suited for defining interfaces, and a bit less messy.
