### ISSUE TITLE
Support for non XCTest subsclasses

### ISSUE THREAD

**Issue by Przemyslaw-Wosko** [MakeAWishFoundation/SwiftyMocky#7]
For now Mocky supports only XCTestCase, i'd be nice to separate framework completely from XCTest, and open support for other platforms.

**Comment by amichnia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add other platforms support (max os, tv os ...)](https://trello.com/c/PurnpgMm/16-add-other-platforms-support-max-os-tv-os)

**Comment by amichnia** [comment]
We can separate it completely, using subspecs. It would look like:

1. Define `MockyAssert` instead of using `XCTAssert`
2. Define subspecs as following:
  - core (default): depends on XCTest, MockyAssert is type alias for XCTAssert
  - inapp: MockyAssert is plain assert
  - nimble: MockyAssert wraps Nimble expect (?)

There are few caveats here:
 - when not default subspec, CocoaPods does not contain other files, like templates etc - we can probably define them as assets

**Comment by amichnia** [comment]
for now, there is one additional `Custom` pod spec. It allows to override how assertions works, and drops XCTest dependency
