### ISSUE TITLE
fatal error: [FATAL] stub return value not specified for ..... Use given!:

### ISSUE THREAD

**Issue by Rameshwar-Gade** [MakeAWishFoundation/SwiftyMocky#92]
Getting "fatal error: [FATAL] stub return value not specified for " after adding new unit test cases.

**Comment by Przemyslaw-Wosko** [comment]
Could you add your unit test snippet here?

**Comment by Rameshwar-Gade** [comment]
After registering matcher I am doing this

let cObservable: Single<MyStructReturnTyoe> = Single.error(DataError.emptyResponse)
        
        let exp = expectation(description: "loading error")
        connector.given(.APIName(card: .value(params), willReturn: cObservable))
        
        cObservable().subscribe(onError: { _ in
            exp.fulfill()

        }).disposed(by: bag)
        
    
       sut.APICall()

**Comment by Przemyslaw-Wosko** [comment]
@Rameshwar-Gade Thanks for sharing!

i'd try just for debug use `.any` matcher, maybe there is an issue with matcher? its hard to say without rest of code.

if this will not work, try to put here more context of code, card struct / class, connector prototcol and i will try to reproduce your issue, we will fix it, if its libray bug

**Comment by amichnia** [comment]
@Rameshwar-Gade - as far as I see, you are specifying given with exact value (some params - I suppose they are some kind of dictionary?).

There are several things to do, in order to solve your problem:
1. First of all - what version of SwiftMocky do you use?
2. Fatal error message you posted is not full I think? It should specify exact method and so on, just to be sure...

As for general things you can do right now, to be sure whole setup is fine:
 - assure all given's are setup before you start main part of test case. Common problem is when stubbed method is being called, before you actually execute given
 - try if changing to .any fixes the issue (as mr Wosko suggested). It might happen, that .value is not properly matched, (then you can fill us with further details, and we will fix it :) )

Let me know if you have any further details I can use to help you out, or if above solved the issue.

**Comment by Rameshwar-Gade** [comment]
@amichnia ,@Przemyslaw-Wosko Thanks for the support, It's working now!

**Comment by amichnia** [comment]
Great, closing in that case.
