### ISSUE TITLE
Help Wanted - protocol confirming to another protocol

### ISSUE THREAD

**Issue by nagarro-vijaykumar04** [MakeAWishFoundation/SwiftyMocky#95]
Hi Team,

While integrating SwiftyMocky, we found one issue. Thought of sharing it here -
If one protocol, say B, is conforming to another protocol, say A and we use SwiftyMocky to generate mocks for both A & B. In that case, since methods of protocol A are not generated/added into BMock, code doesn't compiles and throws error as below:
"BMock doesn't confirm to the protocol A."

Please let us know if we have a workaround for this or it is being fixed soon.

**Comment by Przemyslaw-Wosko** [comment]
Hi @nagarro-vijaykumar04, 
Thanks for raising an issue!
So basically we have 
```
protocol A {
 func protocolAMethod()
}
```
 then we have 
```
protocol B {
 func protocolBMethod()
}
```
and we want to have mock that conforms to both protocols.

Have you tried with typealias? 
```
typealias ProtocolAB = A & B 
```
or new protocol instead? 
```
protocol ProtocolAB: A, B  {} 
```
* i didn't tried it out*

 i will play with this case latter and let you know

**Comment by nagarro-vijaykumar04** [comment]
Hi,
Thanks for your swiftly reply!

The scenario mentioned above is same as your last point i.e.:
`protocol ProtocolAB: A, B {}`

As `protocol ProtocolAB` doesn't have the methods of protocols `A` & `B` as its own definition, while creating mocks for it compiler says, `ProtocolABMock` doesn't confirm with `protocol A` & `protocol B`

**Comment by amichnia** [comment]
@nagarro-vijaykumar04 

Hi, I just verified and inheritance seems to work. Added new test to SwiftyMocky, to verify inheritance case for **version 1.02 +**.

Our test looks like that:

```
//sourcery: AutoMockable
protocol SimpleProtocolWithMethods {
    func simpleMethod()
    func simpleMehtodThatReturns() -> Int
    func simpleMehtodThatReturns(param: String) -> String
    func simpleMehtodThatReturns(optionalParam: String?) -> String?
}

//sourcery: AutoMockable
protocol SimpleProtocolWithProperties {
    var property: String { get set }
    weak var weakProperty: AnyObject! { get set }
    var propertyGetOnly: String { get }
    var propertyOptional: Int? { get set }
    var propertyImplicit: Int! { get set }
}

//sourcery: AutoMockable
protocol SimpleProtocolThatInheritsOtherProtocols: SimpleProtocolWithMethods, SimpleProtocolWithProperties {
}
```

Generated mock `SimpleProtocolThatInheritsOtherProtocolsMock` **adopts both protocols**, and seems to be working fine.

It seems that your problem is not related to protocol inheritance. Anyway - if you could, please provide actual A,B and ProtocolAB code that is breaking generation for you, then I will be able to reopen it and fix the issue. You can reach me on SwiftyMocky slack, if you don't want to post your code here

I'm closing it for now.
